version: "3.3"
services:

  stormy_apollo:
    build: b-apollo
    # ---------------
    # Comment these two lines out
    # after the first run, when the 
    # api keys are all set up.
    #stdin_open: true
    #tty: true
    # ---------------
    volumes:
      - "./b-apollo/bot:/apollo/bot"
    logging:
      driver: "json-file"

  stormy_ginsberg:
    build: b-ginsberg
    # ---------------
    # Comment these two lines out
    # after the first run, when the 
    # api keys are all set up.
    #stdin_open: true
    #tty: true
    # ---------------
    volumes:
      - "./b-ginsberg/bot:/ginsberg/bot"
    logging:
      driver: "json-file"

  stormy_milton:
    build: b-milton
    # ---------------
    # Comment these two lines out
    # after the first run, when the 
    # api keys are all set up.
    #stdin_open: true
    #tty: true
    # ---------------
    volumes:
      - "./b-milton/bot:/milton/bot"
    logging:
      driver: "json-file"

  stormy_tripos:
    build: b-tripos
    # ---------------
    # Comment these two lines out
    # after the first run, when the 
    # api keys are all set up.
    #stdin_open: true
    #tty: true
    # ---------------
    volumes:
      - "./b-tripos/bot:/tripos/bot"

