site_name: pod-bots
site_url: https://pages.charlesreid1.com/pod-bots
repo_name: pod-bots
repo_url: https://git.charlesreid1.com/docker/pod-bots
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
pages:
  - 'Home':         'index.md'
  - 'Running':      'Running.md'
  - 'Volumes':      'Volumes.md'
  - 'Debugging':    'Debugging.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
