site_name: pod-bots
docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'light green'
    accent: 'light green'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
markdown_extensions:
  - admonition
pages:
  - 'Home':         'index.md'
  - 'Running':      'Running.md'
  - 'Volumes':      'Volumes.md'
  - 'Debugging':    'Debugging.md'
